### ISSUE TITLE
compile problems on debian 11

### ISSUE THREAD

**Issue by srperens** [PhilippeBekaert/hdspeconf#4]
Hi, 

I'm trying to compile hdspeconf on Debian 11 and I'm gettings some errors. 

For the packages required I'm running: 

```
sudo apt install libasound2-dev wx3.0-headers libwxgtk3.0-gtk3-dev
````

Then when trying to compile i get alot of errors in the linker stage which points to linker not finding libpng and libcairo for some reason. 

If I then modify Makefile to read 

```
LDFLAGS=-lasound `wx-config --libs` `pkg-config --libs libpng cairo-xlib`
```

then everything compiles ok and I get the hdspeconf binary. 

But when running the hdspeconf binary I get a new errors: 

```
./hdspeconf: /usr/local/lib/x86_64-linux-gnu/libpng16.so.16: no version information available (required by /lib/x86_64-linux-gnu/libwx_gtk3u_core-3.0.so.0)
./hdspeconf: symbol lookup error: /lib/x86_64-linux-gnu/libgdk-3.so.0: undefined symbol: cairo_xlib_surface_create_for_bitmap
```

Any ideas on what I'm doing wrong? 

Thanks a lot!

**Comment by VennStone** [comment]
I was unable to reproduce this error on a fresh install of Debian 11 this afternoon. Installed the following dependencies and it compiled without issues. 

`libasound2-dev wx3.0-headers libwxgtk3.0-gtk3-0v5 build-essential libncurses-dev xz-utils libelf-dev libwxbase3.0-dev libwxgtk3.0-gtk3-dev dkms`

**Comment by srperens** [comment]
Hi, 
Thank you for that information. Good to hear that it does compile OK, and the problem is only on my machine. 

The installation I'm running started out as a Debian minimal installation with no X installed, just SSH, and maybe this is related to that somehow. I have since then added X but this does not change anything, I'm still getting the same errors as above.

**Comment by srperens** [comment]
I have not solved this issue, and currently we can work around it. Thanks anyway!
